apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.7.x"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - source-watcher
  cluster:
    type: kubernetes
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  sync:
    kind: GitRepository
    url: "https://github.com/matheuscscp/flux2-kustomize-helm-example.git"
    ref: "refs/heads/main"
    path: "clusters/staging"
    pullSecret: "flux-system"
  kustomize:
    patches:
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --feature-gates=ExternalArtifact=true
      target:
        kind: Deployment
        name: (kustomize-controller|helm-controller)
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --concurrent=20
        - op: add
          path: /spec/template/spec/containers/0/args/-
          value: --requeue-dependency=5s
      target:
        kind: Deployment
        name: "(kustomize-controller|helm-controller|source-controller)"
