apiVersion: v1
kind: Secret
metadata:
  name: flux-status-server-config
type: Opaque
stringData:
  config.yaml: |
    apiVersion: web.fluxcd.controlplane.io/v1
    kind: Config
    spec:
      {{- toYaml .Values.config | nindent 6 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: flux-status-server-config-dev
type: Opaque
stringData:
  config.yaml: |
    apiVersion: web.fluxcd.controlplane.io/v1
    kind: Config
    spec:
      {{- toYaml .Values.devConfig | nindent 6 }}
